### PR TITLE
Update twitter-and-fitbit-activity.ipynb: Fix checking for valid fitbit data and correct url

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Copy paste error checking for valid fitbit data and correct url to fix

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
@gedankenstuecke Done

**Comment by jacobrosenthal** [comment]
BTW this example still doesnt work for me, Im still figuring out why. I get this error atm
```
AttributeError                            Traceback (most recent call last)
<ipython-input-28-f1c1c789a178> in <module>()
      2 joined_data['steps'] = joined_data['steps'].apply(int)
      3 joined_data = joined_data[joined_data['steps'] != 0]
----> 4 joined_data['year'] = joined_data.index.year

AttributeError: 'Index' object has no attribute 'year'

```

**Comment by gedankenstuecke** [comment]
Thanks! And that's weird, it worked for my own data with the notebook of this PR. Could you post the output of `joined_data.head()` here to see how it looks like?

**Comment by jacobrosenthal** [comment]
@gedankenstuecke 

```
print(joined_data.head())
joined_data = twitter_mean.join(fitbit_steps,how='right')
joined_data['steps'] = joined_data['steps'].apply(int)
joined_data = joined_data[joined_data['steps'] != 0]
joined_data['year'] = joined_data.index.year
Empty DataFrame
Columns: [hashtag, media, url, date, tweets_per_day, steps]
Index: []
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-2c8307d99bc3> in <module>()
      3 joined_data['steps'] = joined_data['steps'].apply(int)
      4 joined_data = joined_data[joined_data['steps'] != 0]
----> 5 joined_data['year'] = joined_data.index.year

AttributeError: 'Index' object has no attribute 'year'
```

**Comment by gedankenstuecke** [comment]
Ah, it seems you don't have data on overlapping dates for `Fitbit` and `Twitter`, that's why the `joined_data` looks like this:

```
Empty DataFrame
Columns: [hashtag, media, url, date, tweets_per_day, steps]
Index: []
```

Is this somewhat expected for you or should there be data? 😄

**Comment by jacobrosenthal** [comment]
Yeah I just noticed my fitbit data is like 1.1kb and the tracker-steps field is empty, so yeah I have a feeling the sync isnt working. I deleted the data and am trying to sync again. I used fitbit for a few months this year and a few times over the past few years, so I would expect some decent data in there.

screen shot 2018-05-20 at 6 07 12 pm

**Comment by jacobrosenthal** [comment]
Just deleted and resynced, same tiny amount of data. Something looks to be wrong with the fitbit sync, where can I report that?

**Comment by gedankenstuecke** [comment]
Oh, that's not good and surprising to hear as we thought the fitbit integration works fine now! Did you press the `update` button on https://oh-fitbit-integration.herokuapp.com/ after logging in to request an update? 

If you could share your `project_member_id` that's on https://www.openhumans.org/activity/fitbit-connection/ (either here or via email at bastian@openhumans.org) I and @mcescalante can have a look what's going wrong there!

**Comment by gedankenstuecke** [comment]
Ok, that issue should have been fixed through https://github.com/OpenHumans/oh-fitbit-integration/pull/14 🎉

**Comment by jacobrosenthal** [comment]
Look good, couple megs now instead of 1kb.
Thanks!

**Comment by gedankenstuecke** [comment]
Great, glad to hear that! And thanks for reporting the problem!

**Comment by gedankenstuecke** [comment]
Thanks for the fixes! 👍 🎉

**Pull request merged**
